config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_empathetic_barracuda.sh
        container: qc.acc_fuchsia_humorous_armadillo
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beige_innocent_hawk.sh
        container: qc.doc_fog_thoughtful_tapir
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.storm_perky_whale.sh
        container: qc.doc_ruby_meticulous_newt
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.coffee_shy_grizzly.sh
        container: qc.doc_aquamarine_logical_heron
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wisteria_analytical_reindeer.sh
        container: qc.lic_rose_playful_kookaburra
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_calm_hawk.sh
        container: qc.met_aquamarine_nurturing_swan
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_clever_okapi.sh
        container: qc.sec_beige_fair_mongoose
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.brown_resourceful_nymph.sh
        container: qc.sty_khaki_careful_weasel
      github.com/EOSC-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.glacier_organized_piranha.sh
        container: qc.sty_yellow_determined_rabbit
      github.com/EOSC-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cayenne_confused_kookaburra.sh
        container: qc.sty_sage_elated_gibbon
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_confident_mongoose.sh
        container: qc.uni_watermelon_tough_octopus
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_relaxed_octopus.sh
        container: qc.ver_cardamom_flexible_catfish
timeout: 5400
