config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-api-server:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-api-server
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.fuchsia_jubilant_cobra.sh
        container: qc.acc_steel_spirited_rabbit
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grape_tranquil_cassowary.sh
        container: qc.doc_cinnabar_mindful_komodo
      github.com/EOSC-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.lagoon_honest_wasp.sh
        container: qc.doc_taupe_upbeat_toucan
      github.com/EOSC-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.glaucous_reserved_porpoise.sh
        container: qc.doc_tide_confident_dragonfly
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cayenne_sweet_piranha.sh
        container: qc.lic_incarnadine_mischievous_kiwi
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.marina_worried_wildcat.sh
        container: qc.met_bronze_sarcastic_caiman
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wave_flexible_cockatoo.sh
        container: qc.sec_khaki_understanding_parrot
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_wondrous_platypus.sh
        container: qc.sty_ecru_curious_cobra
      github.com/EOSC-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lavender_wise_bison.sh
        container: qc.sty_cream_outgoing_donkey
      github.com/EOSC-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_practical_goat.sh
        container: qc.sty_orange_sweet_crow
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.storm_organized_wolf.sh
        container: qc.uni_tan_shy_manta
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_quirky_gorilla.sh
        container: qc.ver_walnut_lucky_impala
timeout: 5400
