config:
  credentials:
  - id: https://github.com/eosc-synergy/sqaaas-api-server
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-api-server:
      branch: main
      credential_tmp: true
      credentials_id: https://github.com/eosc-synergy/sqaaas-api-server
      repo: https://github.com/eosc-synergy/sqaaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.tan_peaceful_macaw.sh
        container: qc.acc_obsidian_reliable_crane
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.harlequin_inspired_eagle.sh
        container: qc.doc_lagoon_assured_panther
      github.com/eosc-synergy/sqaaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.aqua_jubilant_gnu.sh
        container: qc.doc_amaranth_elated_phoenix
      github.com/eosc-synergy/sqaaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_cautious_bat.sh
        container: qc.doc_heather_grumpy_newt
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dawn_resourceful_rhinoceros.sh
        container: qc.lic_red_whimsical_weasel
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ginger_rugged_alpaca.sh
        container: qc.met_ruby_gentle_komodo
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.purple_harmonious_tapir.sh
        container: qc.sec_banana_aware_impala
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flax_smart_macaw.sh
        container: qc.sty_purple_plucky_raccoon
      github.com/eosc-synergy/sqaaas-api-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.rosewater_adaptable_badger.sh
        container: qc.sty_champagne_diligent_tortoise
      github.com/eosc-synergy/sqaaas-api-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.brown_peaceful_sparrow.sh
        container: qc.sty_fuchsia_practical_baboon
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-api-server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.carmine_hopeful_frog.sh
        container: qc.uni_caramel_agile_spider
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_respectful_orca.sh
        container: qc.ver_malachite_bold_clownfish
timeout: 5400
